// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestProject.Entity.Data;

#nullable disable

namespace TestProject.Entity.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20250514102019_HashPassword")]
    partial class HashPassword
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestProject.Entity.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("TestProject.Entity.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 14, 15, 50, 18, 659, DateTimeKind.Local).AddTicks(2792),
                            Email = "user1@email.com",
                            IsDeleted = false,
                            Password = "E2xLjiA8xHMP8lJIXuofAA==:Rj/oJ1ZfkdZJdJH9EIf7Wbo3y3SBNpPnpGQK+ntEGaI=",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 15, 50, 18, 659, DateTimeKind.Local).AddTicks(2804)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 5, 14, 15, 50, 18, 735, DateTimeKind.Local).AddTicks(4137),
                            Email = "user2@email.com",
                            IsDeleted = false,
                            Password = "lNb4kGSHCuzR++cSO/2IHQ==:J1EuK5A/lrmAgxJGbXl3SobqSYqP6cQp2yhfrxwKnUg=",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 15, 50, 18, 735, DateTimeKind.Local).AddTicks(4153)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 5, 14, 15, 50, 18, 810, DateTimeKind.Local).AddTicks(7164),
                            Email = "user3@email.com",
                            IsDeleted = false,
                            Password = "eDjbKcTBMLS2QCTIB0/wcw==:0LtET7k4vuTPiS10aEQI2Prew75tGn7X707mhc4qaMs=",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 15, 50, 18, 810, DateTimeKind.Local).AddTicks(7181)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 5, 14, 15, 50, 18, 887, DateTimeKind.Local).AddTicks(6428),
                            Email = "user4@email.com",
                            IsDeleted = false,
                            Password = "S5QAq+XTbHElgNh2yOu/gQ==:lohzjdYisHDIeNcz+QsD5OWplk2i7G9i6SsleDLO+gA=",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 15, 50, 18, 887, DateTimeKind.Local).AddTicks(6443)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 5, 14, 15, 50, 18, 966, DateTimeKind.Local).AddTicks(3889),
                            Email = "user5@email.com",
                            IsDeleted = false,
                            Password = "Qeh+Bq156b6eglXKzfT3/A==:ORGZFQrSbUwIZP4kKaavZHBC+whdda1lkAvk8MEy6Zk=",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 15, 50, 18, 966, DateTimeKind.Local).AddTicks(3904)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 5, 14, 15, 50, 19, 42, DateTimeKind.Local).AddTicks(9033),
                            Email = "user6@email.com",
                            IsDeleted = false,
                            Password = "mS3iLYlCzmFLDmeum2+1ZQ==:QGB+FISj8KX2HyzczUgi5OcVBjo32xal2mR/PhGQpC0=",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 15, 50, 19, 42, DateTimeKind.Local).AddTicks(9049)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 5, 14, 15, 50, 19, 117, DateTimeKind.Local).AddTicks(7379),
                            Email = "user7@email.com",
                            IsDeleted = false,
                            Password = "g+mZNXmu/6hCr2NacwlHfA==:nW8mqxldBS3V0uOMLYBL2amBVxZiEMCtKjhUm6ue3Ws=",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 15, 50, 19, 117, DateTimeKind.Local).AddTicks(7506)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 5, 14, 15, 50, 19, 192, DateTimeKind.Local).AddTicks(6586),
                            Email = "user8@email.com",
                            IsDeleted = false,
                            Password = "PUmIE+UJxjHX5/Or6WAcew==:qL5o9Z/KX2eqH9t77mvKFSos9embtdexJvo4U0DQOfI=",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 15, 50, 19, 192, DateTimeKind.Local).AddTicks(6592)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 5, 14, 15, 50, 19, 267, DateTimeKind.Local).AddTicks(6376),
                            Email = "user9@email.com",
                            IsDeleted = false,
                            Password = "qRbH+ZJ+JW5I4de9WvkwTg==:N4YXPk63cIYvgna6jIyIUUw+ICpAJRGL8yqMDg4V5dA=",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 15, 50, 19, 267, DateTimeKind.Local).AddTicks(6380)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 5, 14, 15, 50, 19, 342, DateTimeKind.Local).AddTicks(2060),
                            Email = "user10@email.com",
                            IsDeleted = false,
                            Password = "empYNB1T6qz/o9hJwuJRUQ==:Ldp2wKHtVorbhg3epFlK8OwkYTdu+V88tT0SezliwDk=",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 15, 50, 19, 342, DateTimeKind.Local).AddTicks(2064)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 5, 14, 15, 50, 19, 416, DateTimeKind.Local).AddTicks(7526),
                            Email = "user10@email.com",
                            IsDeleted = false,
                            Password = "e0EKMU0JjP70StoKHCHglw==:oHE1e0BgLY5ZyjSxoRyDxt5aNL3nWaaNIALBKlcXyrQ=",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 15, 50, 19, 416, DateTimeKind.Local).AddTicks(7527)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 5, 14, 15, 50, 19, 492, DateTimeKind.Local).AddTicks(5707),
                            Email = "admin1@email.com",
                            IsDeleted = false,
                            Password = "BOQER9jSKEF1jsQg1B3FWA==:XxlB5Dv+rLH3t6EoVrNGm2WBwWKk3F1cU0J4jAtN8UY=",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 5, 14, 15, 50, 19, 492, DateTimeKind.Local).AddTicks(5715)
                        });
                });

            modelBuilder.Entity("TestProject.Entity.Models.User", b =>
                {
                    b.HasOne("TestProject.Entity.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TestProject.Entity.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
