// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestProject.Entity.Data;

#nullable disable

namespace TestProject.Entity.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestProject.Entity.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("TestProject.Entity.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2628),
                            Email = "user1@email.com",
                            IsDeleted = false,
                            Password = "123456",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2639)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2641),
                            Email = "user2@email.com",
                            IsDeleted = false,
                            Password = "123456",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2641)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2643),
                            Email = "user3@email.com",
                            IsDeleted = false,
                            Password = "123456",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2643)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2644),
                            Email = "user4@email.com",
                            IsDeleted = false,
                            Password = "123456",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2645)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2646),
                            Email = "user5@email.com",
                            IsDeleted = false,
                            Password = "123456",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2647)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2648),
                            Email = "user6@email.com",
                            IsDeleted = false,
                            Password = "123456",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2649)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2650),
                            Email = "user7@email.com",
                            IsDeleted = false,
                            Password = "123456",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2651)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2652),
                            Email = "user8@email.com",
                            IsDeleted = false,
                            Password = "123456",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2652)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2654),
                            Email = "user9@email.com",
                            IsDeleted = false,
                            Password = "123456",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2654)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2656),
                            Email = "user10@email.com",
                            IsDeleted = false,
                            Password = "123456",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2656)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2657),
                            Email = "user10@email.com",
                            IsDeleted = false,
                            Password = "123456",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2658)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2659),
                            Email = "admin1@email.com",
                            IsDeleted = false,
                            Password = "123456",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 5, 14, 12, 4, 31, 811, DateTimeKind.Local).AddTicks(2660)
                        });
                });

            modelBuilder.Entity("TestProject.Entity.Models.User", b =>
                {
                    b.HasOne("TestProject.Entity.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TestProject.Entity.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
